### ISSUE TITLE
Not working with multiple fonts styles

### ISSUE THREAD

**Issue by jvolker** [kylebarron/openmaptiles-fonts#2]
Thanks a lot for hosting these font files.

Unfortunately what you are suggesting  (`"glyphs": "https://cdn.jsdelivr.net/gh/kylebarron/openmaptiles-fonts/fonts/{fontstack}/{range}.pbf"`) doesn't work with multi font styles like [Positron](https://github.com/openmaptiles/positron-gl-style) as described [here](https://github.com/openmaptiles/fonts/issues/17).

The style is requesting `https://cdn.jsdelivr.net/gh/kylebarron/openmaptiles-fonts/fonts/Metropolis%20Regular,Noto%20Sans%20Regular/0-255.pbf` and fails with a 401 error.

Do you have any suggestions?

Thanks.

**Comment by kylebarron** [comment]
Well, that's expected. If you need to serve `Metropolis%20Regular,Noto%20Sans%20Regular` from static files, you'd need to have a folder named that, including the comma. Usually a list of font selections (i.e. in CSS) mean "choose the first one that exists". So if you know `Metropolis Regular` exists, then you can remove `Noto Sans` from the list.

So just fork positron and change
```
        "text-font": ["Metropolis Medium Italic", "Noto Sans Italic"],
```
to
```
        "text-font": ["Metropolis Medium Italic"],
```

Closing as I don't think this is related to this font repository.

**Comment by jvolker** [comment]
Thanks for the explanation.
